### ISSUE TITLE
Files keep showing up as corrupted

### ISSUE THREAD

**Issue by Mistabay** [Emy69/CoomerDL#34]
the video downloads for like 2Mb and then gets stuck for 2 minutes with this error on the screenshot.
![изображение](https://github.com/user-attachments/assets/ba0f73c3-81d2-4bf9-bc6e-e113a81c55a1)
I'm thinking its the website issue itself but if there is an actual fix, i would appreciate knowing it.

**Comment by xxIAMIxx** [comment]
> the video downloads for like 2Mb and then gets stuck for 2 minutes with this error on the screenshot.
> ![изображение](https://github.com/user-attachments/assets/ba0f73c3-81d2-4bf9-bc6e-e113a81c55a1)
> I'm thinking its the website issue itself but if there is an actual fix, i would appreciate knowing it.

Same problem for me.
And with big files the program doesn't work and need to forced closure.
Thanks a lot

**Comment by yhyhlolol** [comment]
same problem here

**Comment by MachiavelliSeraphim** [comment]
also having the same issues

**Comment by 01000011-shade** [comment]
The problem is definitely on the website side of things, but the tool doesn't really handle these failures gracefully and puts itself into an infinite loop of trying to download something that will never complete. The logic flow right now is:
- On first attempt: attempt to download file, fail with IncompleteRead exception, and then append to `self.failed_files` list. The tool continues to iterate through futures, so it doesn't get caught here and other files will continue.
https://github.com/Emy69/CoomerDL/blob/f44f77de6cdad603f91277f870ed61e3bb45bbd9/downloader/downloader.py#L253-L255

- Second+ attempts: The problem arises here, when we retry any failed files using the same `process_media_element` function that originally populated the `self.failed_files` list. I can't say for certain that it's repopulating, and, if it is, where exactly it's getting stuck, but I do know it gets caught in an infinite loop with this particular error that's been popping up over the last few weeks.
https://github.com/Emy69/CoomerDL/blob/f44f77de6cdad603f91277f870ed61e3bb45bbd9/downloader/downloader.py#L374-L380

I "fixed" this by removing the `self.failed_files.append(media_url)` in line 255 so the failed files list isn't populated (and doesn't get stuck), but this is only really a band-aid and means there will be no retries at all, even for stuff that fails for any other reason. I also added in an `os.remove(filepath)` in its place so the partially downloaded files will be removed and would be attempted on a rerun, which could be a bit annoying, but a bit better than an infinite loop.

```
except Exception as e:
    self.log(self.tr("Error downloading: {e}", e=e))
    os.remove(filepath)
```
